name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: start redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 5

      - name: Git checkout
        uses: actions/checkout@v2

      - name: test and build
        uses: icepuma/rust-action@master
        with:
          args: cargo test && cargo build --release

